spring:
  profiles:
    active:
    - dev
---
spring:
#  profiles:dev #开发环境
  application:
    name: spring-cloud-config-server-github-dev
---
spring:
#  profiles:test #测试环境
  application:
    name: spring-cloud-config-server-github-test
#必须以UTF-8格式保存
    