spring:
  profiles:
    active:
    - dev
---
server:
  port: 8081
spring:
#  profiles:dev #开发环境
  application:
    name: spring-cloud-config-server-github-dev
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
---
spring:
#  profiles:test #测试环境
  application:
    name: spring-cloud-config-server-github-test
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka
#必须以UTF-8格式保存